version: '3.8'

networks:
  clra_macvlan:
    external: true
  #bridge_prometheus:
  #  external: true

volumes:
  vol_nfs_grafana:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.20,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/grafana"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      clra_macvlan:
        ipv4_address: 192.168.1.54
    #  bridge_prometheus:
    ports:
      - "3000:3000"
    volumes:
      - vol_nfs_grafana:/var/lib/grafana
    restart: always