version: '3'

networks:
  clra_macvlan:
    external: true

volumes:
  vol_nfs_esphome:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.15,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/esphome"

services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - vol_nfs_esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      clra_macvlan:
        ipv4_address: 10.0.2.30
        ipv6_address: 2001:db8:cafe::30
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe
      - ESPHOME_DASHBOARD_USE_PING=true