volumes:
  vol_prod:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.15,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/portainer"
services:
  app:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_prod:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.homelab.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=production"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: unless-stopped
    networks:
      clra_macvlan:
        ipv4_address: 10.0.2.13
        ipv6_address: 2001:db8:cafe::13
      clra_bridge:
networks:
  clra_macvlan:
    external: true
  clra_bridge:
    external: true