http:
  routers:
    dsm-router: # Synology DSM Router
      entryPoints:
        - websecure
      rule: "Host(`dsm.domain`)"
      service: dsm-service
      tls:
        certResolver: production
  services:
    dsm-service: # Synology DSM Service
      loadbalancer:
        passHostHeader: true
        servers:
          - url: "https://10.0.2.15:5001"
tcp:
  routers:
    vpn-router: # Synology OpenVPN Router
      entryPoints:
        - websecure
      rule: "HostSNI(`*`)"
      service: vpn-service
  services:
    vpn-service: # Synology OpenVPN Service
      loadbalancer:
        servers:
          - address: "10.0.2.15:1194"