global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
  level: INFO
  format: json
  filePath: /etc/traefik/logs/traefik/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
accesslog:
  format: json
  filePath: /etc/traefik/logs/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do insecure production
api:
  dashboard: true
  debug: true
#   insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  # -- (Optional) Add custom Entrypoint
  # custom:
  #   address: :8080

# -- (Optional) Disable TLS Cert verification check (must be true if redirecting to self-signed services)
# This tells Traefik to ignore self-signed out of the box insecure certificates generated by Synology DSM, Proxmox, etc. 
serversTransport:
  insecureSkipVerify: true

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       -- (Optional) Remove this section, when using DNS Challenge
      httpChallenge:
        entryPoint: web
#       -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

  production:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       -- (Optional) Remove this section, when using DNS Challenge
      httpChallenge:
        entryPoint: web
#       -- (Optional) Configure DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
    # -- (Optional) Explicitly choose a network for Docker containers added with labels
    network: clra_macvlan
  file:
    # -- (Optional) Use this for static routing and services outside Docker
    directory: /etc/traefik/conf/
    watch: true