version: "2.1"

volumes:
  vol_prod:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.10,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/heimdall"

networks:
  clra_macvlan:
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      clra_macvlan:
        ipv4_address: 10.0.2.26
    environment:
      - TZ=Australia/Sydney
    volumes:
      - vol_prod:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped