version: "3.8"

volumes:
  vol_prod:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.10,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/uptime_kuma"

networks:
  clra_macvlan:
    external: true
  prometheus_default:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    networks:
      clra_macvlan:
        ipv4_address: 10.0.2.27
      prometheus_default:
    ports:
      - 3001:3001
    volumes:
      - vol_prod:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped