version: '3'

networks:
  clra_macvlan:
    external: true

volumes:
  vol_nfs_homeassistant:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.2.10,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/volume1/nfs_docker_prod/home_assistant"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - vol_nfs_homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      clra_macvlan:
        ipv4_address: 10.0.2.24